QLCuaHangVali/Areas/Admin/Controllers/ValiController.cs
using PagedList;
using QLCuaHangVali.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangVali.Areas.Admin.Controllers
{
    public class ValiController : BaseController
    {
        // GET: Admin/Vali
        ValiDBDataContext db = new ValiDBDataContext();
        //lay list danh muc
        public void SetViewBag(int? selectedId = null)
        {
            List<THUONGHIEU> listThuongHieu = db.THUONGHIEUs.ToList();
            List<SIZEVALI> listSize = db.SIZEVALIs.ToList();
            List<DANHMUCVALI> listDanhMuc = db.DANHMUCVALIs.ToList();
            ViewBag.DMID = new SelectList(listDanhMuc, "madanhmuc", "tendanhmuc");
            ViewBag.SizeID = new SelectList(listSize, "masize", "tensize");
            ViewBag.CategoryID = new SelectList(listThuongHieu, "mathuonghieu","tenthuonghieu");
        }
        // GET: Vali
        public ActionResult Index(int ? page)
        {
            if (page == null) page = 1;
            //var all_vl = (from vl in db.VALIs select vl).OrderBy( m => m.mavali);
            var all_vali = db.VALIs.Where(p => p.trangthai == true).OrderBy(p => p.mavali);
            int pageSize = 9;
            int pageNum = page ?? 1;
            return View(all_vali.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Details(int id)
        {
            VALI find = db.VALIs.FirstOrDefault(m => m.mavali == id);
            if (find == null)
                return HttpNotFound();
            return View(find);
        }

        public ActionResult Create()
        {
            SetViewBag();
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, VALI vl)
        {
            var tenvali = collection["tenvali"];
            var mathuonghieu = int.Parse(collection["mathuonghieu"]);
            var masize = int.Parse(collection["masize"]);
            var madanhmuc = int.Parse(collection["madanhmuc"]);
            var anhvali = collection["anhvali"];
            var mota = collection["mota"];
            var tukhoa = collection["tukhoa"];
            var soluongton = int.Parse(collection["soluongton"]);
            var gia = Convert.ToDecimal(collection["gia"]);
            var giakhuyenmai = Convert.ToDecimal(collection["giakhuyenmai"]);
            var ngaytao = Convert.ToDateTime(collection["ngaytao"]);
            var trangthai = Convert.ToBoolean(collection["trangthai"]);
            var chatlieu = collection["chatlieu"];
            var kichthuoc = collection["kichthuoc"];
            var thetich = collection["thetich"];
            var banhxe = collection["banhxe"];
            var khoa = collection["khoa"];
            var tienich = collection["tienich"];
            var linkvideo = collection["linkvideo"];

            if (string.IsNullOrEmpty(tenvali))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                vl.tenvali = tenvali.ToString();
                vl.mathuonghieu = int.Parse(mathuonghieu.ToString());
                vl.masize = int.Parse(masize.ToString());
                vl.madanhmuc = int.Parse(madanhmuc.ToString());
                vl.anhvali = anhvali.ToString();
                vl.mota = mota.ToString();
                vl.tukhoa = tukhoa.ToString();
                vl.soluongton = int.Parse(soluongton.ToString());
                vl.gia = Convert.ToDecimal(gia.ToString());
                vl.giakhuyenmai = Convert.ToDecimal(giakhuyenmai.ToString());
                vl.ngaytao = Convert.ToDateTime(ngaytao);
                vl.trangthai = Convert.ToBoolean(trangthai);
                vl.chatlieu = chatlieu.ToString();
                vl.kichthuoc = kichthuoc.ToString();
                vl.thetich = thetich.ToString();
                vl.banhxe = banhxe.ToString();
                vl.khoa = khoa.ToString();
                vl.tienich = tienich.ToString();
                vl.linkvideo = linkvideo.ToString();
                db.VALIs.InsertOnSubmit(vl);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public ActionResult Edit(int id)
        {
            VALI find = db.VALIs.FirstOrDefault(m => m.mavali == id);
            if (find == null)
                return HttpNotFound();
            SetViewBag();
            return View(find);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var vl = db.VALIs.First(m => m.mavali == id);
            var tenvali = collection["tenvali"];
            var mathuonghieu = int.Parse(collection["mathuonghieu"]);
            var masize = int.Parse(collection["masize"]);
            var madanhmuc = int.Parse(collection["madanhmuc"]);
            var anhvali = collection["anhvali"];
            var mota = collection["mota"];
            var tukhoa = collection["tukhoa"];
            var soluongton = int.Parse(collection["soluongton"]);
            var gia = Convert.ToDecimal(collection["gia"]);
            var giakhuyenmai = Convert.ToDecimal(collection["giakhuyenmai"]);
            var ngaytao = Convert.ToDateTime(collection["ngaytao"]);
            var trangthai = Convert.ToBoolean(collection["trangthai"]);
            var chatlieu = collection["chatlieu"];
            var kichthuoc = collection["kichthuoc"];
            var thetich = collection["thetich"];
            var banhxe = collection["banhxe"];
            var khoa = collection["khoa"];
            var tienich = collection["tienich"];
            var linkvideo = collection["linkvideo"];
            vl.mavali = id;
            if (string.IsNullOrEmpty(tenvali))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                vl.tenvali = tenvali.ToString();
                vl.mathuonghieu = int.Parse(mathuonghieu.ToString());
                vl.masize = int.Parse(masize.ToString());
                vl.madanhmuc = int.Parse(madanhmuc.ToString());
                vl.anhvali = anhvali.ToString();
                vl.mota = mota.ToString();
                vl.tukhoa = tukhoa.ToString();
                vl.soluongton = int.Parse(soluongton.ToString());
                vl.gia = Convert.ToDecimal(gia.ToString());
                vl.giakhuyenmai = Convert.ToDecimal(giakhuyenmai.ToString());
                vl.ngaytao = Convert.ToDateTime(ngaytao);
                vl.trangthai = Convert.ToBoolean(trangthai);
                vl.chatlieu = chatlieu.ToString();
                vl.kichthuoc = kichthuoc.ToString();
                vl.thetich = thetich.ToString();
                vl.banhxe = banhxe.ToString();
                vl.khoa = khoa.ToString();
                vl.tienich = tienich.ToString();
                vl.linkvideo = linkvideo.ToString();
                UpdateModel(vl);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            VALI find = db.VALIs.FirstOrDefault(m => m.mavali == id && m.trangthai == true);
            if (find == null)
                return HttpNotFound();
            return View(find);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var Del_vl = db.VALIs.Where(m => m.mavali == id && m.trangthai == true).First();
            if(Del_vl != null)
            {
                Del_vl.trangthai = false;
            }
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/AnhVali/" + file.FileName));
            return file.FileName;
        }
    }
}

QLCuaHangVali/Controllers/ValiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangVali.Controllers
{
    public class ValiController : Controller
    {
        // GET: Vali
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLCuaHangVali/Areas/Admin/Views/Vali/Create.cshtml
@model QLCuaHangVali.Models.VALI

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
@section header{
    <link href="~/Public/admin/css/cssAdmin.css" rel="stylesheet" />
    <h2 style="text-align: center">Tạo mới sản phẩm</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group form-create">
        <label class="col-md-2 ">Tên Vali</label>
        <div class="col-md-7 ">
            @Html.EditorFor(model => model.tenvali, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tenvali, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group form-create">
        <label class="col-md-2">Thương hiệu</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.mathuonghieu, (ViewBag.CategoryID as SelectList), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mathuonghieu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Kích thước</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.masize, (ViewBag.SizeID as SelectList), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.masize, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Danh mục</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.madanhmuc, (ViewBag.DMID as SelectList), new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.madanhmuc, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group form-create">
            <label class="col-md-2">Hình ảnh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.anhvali, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.anhvali, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <div class="form-group form-create">
        <label class="col-md-2">Ảnh vali</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.anhvali, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.anhvali, "", new { @class = "text-danger" })
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                   style="display:none;" />
            <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            @*<img src="~/Content/AnhVali/@Model.anhvali" style="border-radius: 50%; height: 120px; width: 120px;" id="pictureUpload" />*@
        </div>
    </div>
    <!--  Lam nut chon anh  -->
    <script src="~/Public/homepage/js/jquery-2.1.4.min.js"></script>
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });
        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);

                $.ajax(
                    {
                        type: 'POST',
                        url: '/Vali/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {

                            $('#pictureUpload').attr('src', "/Content/AnhVali/" + urlImage);
                            $('#anhvali').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>

    <!--  End- Lam nut chon anh  -->

    <div class="form-group form-create">
        <label class="col-md-2">Mô tả</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.mota, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Từ khóa</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.tukhoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tukhoa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Số lượng tồn</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.soluongton, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.soluongton, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Giá</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Giá khuyến mãi</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.giakhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.giakhuyenmai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Ngày tạo</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ngaytao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ngaytao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Trạng thái</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.trangthai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Chất liệu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.chatlieu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.chatlieu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Kích thước</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.kichthuoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.kichthuoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Thể tích</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.thetich, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.thetich, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Bánh xe</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.banhxe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.banhxe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Khóa</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.khoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.khoa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Tiện ích</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.tienich, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tienich, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <label class="col-md-2">Đường dẫn</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.linkvideo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.linkvideo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group form-create">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo mới" class="btn btn-success" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Trở về", "Index")
    </div>
}

QLCuaHangVali/Areas/Admin/Views/Vali/Delete.cshtml
@model QLCuaHangVali.Models.VALI

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
@section header{
    <link href="~/Public/admin/css/cssAdmin.css" rel="stylesheet" />
    <h2 style="text-align: center">Xóa Sản Phẩm</h2>

    <div>

        <hr />
        <dl class="dl-horizontal">



            <table class="table" border="1px" style="text-align: center">
                <tr>
                    <th>Tên vali </th>
                    <td> @Html.DisplayFor(model => model.tenvali)</td>
                </tr>
                <tr>
                    <th>Tên thương hiệu </th>
                    <td> @Html.DisplayFor(model => model.THUONGHIEU.tenthuonghieu)</td>
                </tr>
                <tr>
                    <th>Size </th>
                    <td> @Html.DisplayFor(model => model.SIZEVALI.tensize)</td>
                </tr>
                <tr>
                    <th>Tên danh mục  </th>
                    <td> @Html.DisplayFor(model => model.DANHMUCVALI.tendanhmuc)</td>
                </tr>
                <tr>
                    <th>Ảnh vali </th>
                    <td>
                        <img class="images_Product_Admin" src="~/Content/AnhVali/@Html.DisplayFor(model => model.anhvali)" />
                    </td>
                </tr>
                <tr>
                    <th>Mô tả </th>
                    <td> @Html.DisplayFor(model => model.mota)</td>
                </tr>
                <tr>
                    <th>Từ khóa </th>
                    <td> @Html.DisplayFor(model => model.tukhoa)</td>
                </tr>
                <tr>
                    <th>Số lượng tồn </th>
                    <td> @Html.DisplayFor(model => model.soluongton)</td>
                </tr>
                <tr>
                    <th>Giá gốc </th>
                    <td> @Html.DisplayFor(model => model.gia)</td>
                </tr>
                <tr>
                    <th>Giá khuyến mãi </th>
                    <td> @Html.DisplayFor(model => model.giakhuyenmai)</td>
                </tr>
                <tr>
                    <th>Ngày nhập hàng </th>
                    <td> @Html.DisplayFor(model => model.ngaytao)</td>
                </tr>
                <tr>
                    <th>Trạng thái </th>
                    <td> @Html.DisplayFor(model => model.trangthai)</td>
                </tr>
                <tr>
                    <th>Chất liệu </th>
                    <td> @Html.DisplayFor(model => model.chatlieu)</td>
                </tr>
                <tr>
                    <th>Kích thước</th>
                    <td> @Html.DisplayFor(model => model.kichthuoc)</td>
                </tr>
                <tr>
                    <th>Thể tích </th>
                    <td> @Html.DisplayFor(model => model.thetich)</td>
                </tr>
                <tr>
                    <th>Bánh xe</th>
                    <td> @Html.DisplayFor(model => model.banhxe)</td>
                </tr>
                <tr>
                    <th>Khóa </th>
                    <td> @Html.DisplayFor(model => model.khoa)</td>
                </tr>
                <tr>
                    <th>Tiện ích</th>
                    <td> @Html.DisplayFor(model => model.tienich)</td>
                </tr>


            </table>


        </dl>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
            <div style="text-align: right">
                @Html.ActionLink("Quay lại", "Index")
            </div>}
    </div>

}

QLCuaHangVali/Areas/Admin/Views/Vali/Details.cshtml
@model QLCuaHangVali.Models.VALI

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
@section header{
    <link href="~/Public/admin/css/cssAdmin.css" rel="stylesheet" />
    <h2 style="text-align: center">Chi Tiết Sản Phẩm</h2>

    <div>

        <hr />
        <dl class="dl-horizontal">



            <table class="table" border="1px" style="text-align: center">
                <tr>
                    <th>Tên vali </th>
                    <td> @Html.DisplayFor(model => model.tenvali)</td>
                </tr>
                <tr>
                    <th>Tên thương hiệu </th>
                    <td> @Html.DisplayFor(model => model.THUONGHIEU.tenthuonghieu)</td>
                </tr>
                <tr>
                    <th>Size </th>
                    <td> @Html.DisplayFor(model => model.SIZEVALI.tensize)</td>
                </tr>
                <tr>
                    <th>Tên danh mục  </th>
                    <td> @Html.DisplayFor(model => model.DANHMUCVALI.tendanhmuc)</td>
                </tr>
                <tr>
                    <th>Ảnh vali </th>
                    <td>
                        <img class="images_Product_Admin" src="~/Content/AnhVali/@Html.DisplayFor(model => model.anhvali)" />
                    </td>
                </tr>
                <tr>
                    <th>Mô tả </th>
                    <td> @Html.DisplayFor(model => model.mota)</td>
                </tr>
                <tr>
                    <th>Từ khóa </th>
                    <td> @Html.DisplayFor(model => model.tukhoa)</td>
                </tr>
                <tr>
                    <th>Số lượng tồn </th>
                    <td> @Html.DisplayFor(model => model.soluongton)</td>
                </tr>
                <tr>
                    <th>Giá gốc </th>
                    <td> @Html.DisplayFor(model => model.gia)</td>
                </tr>
                <tr>
                    <th>Giá khuyến mãi </th>
                    <td> @Html.DisplayFor(model => model.giakhuyenmai)</td>
                </tr>
                <tr>
                    <th>Ngày nhập hàng </th>
                    <td> @Html.DisplayFor(model => model.ngaytao)</td>
                </tr>
                <tr>
                    <th>Trạng thái </th>
                    <td> @Html.DisplayFor(model => model.trangthai)</td>
                </tr>
                <tr>
                    <th>Chất liệu </th>
                    <td> @Html.DisplayFor(model => model.chatlieu)</td>
                </tr>
                <tr>
                    <th>Kích thước</th>
                    <td> @Html.DisplayFor(model => model.kichthuoc)</td>
                </tr>
                <tr>
                    <th>Thể tích </th>
                    <td> @Html.DisplayFor(model => model.thetich)</td>
                </tr>
                <tr>
                    <th>Bánh xe</th>
                    <td> @Html.DisplayFor(model => model.banhxe)</td>
                </tr>
                <tr>
                    <th>Khóa </th>
                    <td> @Html.DisplayFor(model => model.khoa)</td>
                </tr>
                <tr>
                    <th>Tiện ích</th>
                    <td> @Html.DisplayFor(model => model.tienich)</td>
                </tr>


            </table>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/@Html.DisplayFor(model=>model.linkvideo)" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


        </dl>

    </div>
    <p>
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.mavali }) |
        @Html.ActionLink("Quay về", "Index")
    </p>

}

QLCuaHangVali/Areas/Admin/Views/Vali/Index.cshtml
@model PagedList.IPagedList<QLCuaHangVali.Models.VALI>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

@section header{

    <link href="~/Public/admin/css/cssAdmin.css" rel="stylesheet" />
    <h2 style="text-align: center">Quản lý sản phẩm</h2>
    <a style="padding-bottom: 20px" href="@Url.Action("Create","Vali")">
        <input type="button" value="Thêm mới sản phẩm" class="btn btn-success" />
    </a>
   <hr />
     
    <table class="table" border="1px">
        <tr>
            <th>Mã Vali</th>
            <th>Tên Vali</th>
            <th>Thương Hiệu </th>
            <th>Size</th>
            <th>Danh Mục </th>
            <th>Hình</th>
            <th>Số lượng tồn</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.mavali</td>
                <td>@item.tenvali</td>
                <td>@item.THUONGHIEU.tenthuonghieu</td>
                <td>@item.SIZEVALI.tensize</td>
                <td>@item.DANHMUCVALI.tendanhmuc</td>
                <td>
                    <img class="images_Product_Admin" src="~/Content/AnhVali/@item.anhvali" />
                </td>
                <td>@item.soluongton</td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.mavali }) |
        @Html.ActionLink("Chi tiết", "Details", new { id = item.mavali }) |
        @Html.ActionLink("Xóa", "Delete", new { id = item.mavali })
            

                </td>

            </tr>
        }
    </table>
    <div>
        <div>
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /
            @Model.PageCount
        </div>
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new
            {
                page = page
            }))
        </div>
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
    <style type="text/css">
        #mau-nut a {
            clear: both;
            background-color: blue;
            color: snow;
        }

            #mau-nut a:hover {
                background-color: darkcyan;
                color: snow;
            }
    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function () {
            var maxLength = 100;
            $(".show-read-more").each(function () {
                var myStr = $(this).text();
                if ($.trim(myStr).length > maxLength) {
                    var newStr = myStr.substring(0, maxLength);
                    var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                    $(this).empty().html(newStr);

                    $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                    $(this).append('<span class="more-text">' + removedStr +
                        '</span>');
                }
            });
            $(".read-more").click(function () {
                $(this).siblings(".more-text").contents().unwrap();
                $(this).remove();
            });
        });
    </script>
    <style>
        .show-read-more .more-text {
            display: none;
        }
    </style>
}