QLCuaHangVali/Areas/Admin/Controllers/KhuyenMaiController.cs
using PagedList;
using QLCuaHangVali.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangVali.Areas.Admin.Controllers
{
    public class KhuyenMaiController : Controller
    {
        // GET: Admin/ThuongHieu
        ValiDBDataContext db = new ValiDBDataContext();
        // GET: Vali
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            var all_vl = (from vl in db.PHIEUKHUYENMAIs select vl).OrderBy(m => m.makhuyenmai);
            int pageSize = 6;
            int pageNum = page ?? 1;
            return View(all_vl.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, PHIEUKHUYENMAI km)
        {

            var tenkhuyenmai = collection["tenkhuyenmai"];
            var phantram = collection["phantram"];
            var tienkhuyenmai = Convert.ToDecimal(collection["tienkhuyenmai"]);
            var ngaybatdau = Convert.ToDateTime(collection["ngaybatdau"]);
            var ngayketthuc = Convert.ToDateTime(collection["ngayketthuc"]);



            if (string.IsNullOrEmpty(tenkhuyenmai))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {

                km.tenkhuyenmai = tenkhuyenmai.ToString();
                km.phantram = phantram.ToString();
                km.tienkhuyenmai = tienkhuyenmai;
                km.ngaybatdau = ngaybatdau;
                km.ngayketthuc = ngayketthuc;

                db.PHIEUKHUYENMAIs.InsertOnSubmit(km);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        public ActionResult Edit(int id)
        {
            PHIEUKHUYENMAI find = db.PHIEUKHUYENMAIs.FirstOrDefault(m => m.makhuyenmai == id);
            if (find == null)
                return HttpNotFound();
            return View(find);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var km = db.PHIEUKHUYENMAIs.First(m => m.makhuyenmai == id);
            var tenkhuyenmai = collection["tenkhuyenmai"];
            var phantram = collection["phantram"];
            var tienkhuyenmai = Convert.ToDecimal(collection["tienkhuyenmai"]);
            var ngaybatdau = Convert.ToDateTime(collection["ngaybatdau"]);
            var ngayketthuc = Convert.ToDateTime(collection["ngayketthuc"]);

            km.makhuyenmai = id;
            if (string.IsNullOrEmpty(tenkhuyenmai))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                km.tenkhuyenmai = tenkhuyenmai.ToString();
                km.phantram = phantram.ToString();
                km.tienkhuyenmai = tienkhuyenmai;
                km.ngaybatdau = ngaybatdau;
                km.ngayketthuc = ngayketthuc;

                UpdateModel(km);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            PHIEUKHUYENMAI find = db.PHIEUKHUYENMAIs.FirstOrDefault(m => m.makhuyenmai == id);
            if (find == null)
                return HttpNotFound();
            return View(find);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var Del_th = db.PHIEUKHUYENMAIs.Where(m => m.makhuyenmai == id).First();
            db.PHIEUKHUYENMAIs.DeleteOnSubmit(Del_th);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

QLCuaHangVali/Areas/Admin/Views/KhuyenMai/Create.cshtml
@model QLCuaHangVali.Models.PHIEUKHUYENMAI

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

@section header{
    <h2 style="text-align: center">Thêm mới khuyến mãi</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-md-2 ">Tên khuyến mãi</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tenkhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tenkhuyenmai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 ">Phần trăm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phantram, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phantram, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 ">Tiền khuyến mãi </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tienkhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tienkhuyenmai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 ">Ngày bắt đầu </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngaybatdau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngaybatdau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 ">Ngày kết thúc </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngayketthuc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngayketthuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
}

QLCuaHangVali/Areas/Admin/Views/KhuyenMai/Delete.cshtml
@model QLCuaHangVali.Models.PHIEUKHUYENMAI

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

@section header{
    <h2 style="text-align: center">Xóa khuyến mãi</h2>


    <div>
        <hr />
        <dl class="dl-horizontal">
            <table class="table" border="1px" style="text-align: center">
                <tr>
                    <th>Tên khuyến mãi </th>
                    <td> @Html.DisplayFor(model => model.tenkhuyenmai)</td>
                </tr>
                <tr>
                    <th>Phần trăm</th>
                    <td> @Html.DisplayFor(model => model.phantram)</td>
                </tr>
                <tr>
                    <th>Tiền khuyến mãi</th>
                    <td> @Html.DisplayFor(model => model.tienkhuyenmai)</td>
                </tr>
                <tr>
                    <th>Ngày bắt đầu</th>
                    <td> @Html.DisplayFor(model => model.ngaybatdau)</td>
                </tr>
                <tr>
                    <th>Ngày kết thúc</th>
                    <td> @Html.DisplayFor(model => model.ngayketthuc)</td>
                </tr>
            </table>


        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
            <div style="text-align: right">
                @Html.ActionLink("Quay lại", "Index")
            </div>

        }
    </div>

}

QLCuaHangVali/Areas/Admin/Views/KhuyenMai/Edit.cshtml
@model QLCuaHangVali.Models.PHIEUKHUYENMAI
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

@section header{
    <h2 style="text-align: center">Sửa thông tin khuyến mãi</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.makhuyenmai)

            <div class="form-group">
                <label class="col-md-2">Tên thương hiệu</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tenkhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tenkhuyenmai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2">Phần trăm</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phantram, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phantram, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2">Tiền khuyến mãi</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tienkhuyenmai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tienkhuyenmai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2">Ngày bắt đầu</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngaybatdau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngaybatdau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2">Ngày kết thúc</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngayketthuc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngayketthuc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
}

QLCuaHangVali/Areas/Admin/Views/KhuyenMai/Index.cshtml
@model PagedList.IPagedList<QLCuaHangVali.Models.PHIEUKHUYENMAI>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
@section header{

    <link href="~/Public/admin/css/cssAdmin.css" rel="stylesheet" />
    <h2 style="text-align: center">Quản lý khuyến mãi</h2>
    <a style="padding-bottom: 20px" href="@Url.Action("Create","KhuyenMai")">
        <input type="button" value="Thêm mới sản phẩm" class="btn btn-success" />
    </a>
    <hr />

    <table class="table" border="1px">
        <tr>
            <th>Mã Khuyến Mãi</th>
            <th>Tên Khuyến Mãi</th>
            <th>Phần Trăm</th>
            <th>Tiền Khuyến Mãi</th>
            <th>Ngày bắt đầu </th>
            <th>Ngày kết thúc</th>

            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.makhuyenmai</td>
                <td>@item.tenkhuyenmai</td>
                <td>@item.phantram </td>
                <td>@item.tienkhuyenmai </td>
                <td>@item.ngaybatdau </td>
                <td>@item.ngayketthuc </td>


                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.makhuyenmai }) |

                    @Html.ActionLink("Xóa", "Delete", new { id = item.makhuyenmai })


                </td>

            </tr>
        }
    </table>
    <div>
        <div>
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /
            @Model.PageCount
        </div>
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new
            {
                page = page
            }))
        </div>
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
    <style type="text/css">
        #mau-nut a {
            clear: both;
            background-color: blue;
            color: snow;
        }

            #mau-nut a:hover {
                background-color: darkcyan;
                color: snow;
            }
    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function () {
            var maxLength = 100;
            $(".show-read-more").each(function () {
                var myStr = $(this).text();
                if ($.trim(myStr).length > maxLength) {
                    var newStr = myStr.substring(0, maxLength);
                    var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                    $(this).empty().html(newStr);

                    $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                    $(this).append('<span class="more-text">' + removedStr +
                        '</span>');
                }
            });
            $(".read-more").click(function () {
                $(this).siblings(".more-text").contents().unwrap();
                $(this).remove();
            });
        });
    </script>
    <style>
        .show-read-more .more-text {
            display: none;
        }
    </style>
}