QLCuaHangVali/Controllers/NguoiDungController.cs
using QLCuaHangVali.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace QLCuaHangVali.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        ValiDBDataContext data = new ValiDBDataContext();
        [HttpGet]
        public ActionResult DangKy()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KHACHHANG kh)
        {
            //Gan cac gia tri nguoi dung nhap lieu
            var hoten = collection["name"];
            var tendn = collection["username"];
            var dienthoai = collection["sodienthoai"];
            var matkhau = collection["password"];
            var matkhaunhaplai = collection["ConfirmPassword"];
            var email = collection["Email"];
            //var anhdaidien = collection["anhdaidien"];
            //var diachi = collection["diachi"];
            //var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được bỏ trống";
            }
            else if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Phải nhập điện thoại";
            }
            else
            {
                //Gan cac gia tri cho doi tuong duoc tao moi(kh)
                kh.tenkhachhang = hoten;
                kh.taikhoankh = tendn;
                kh.matkhau = matkhau;
                kh.email = email;
                //kh.diachi = diachi;
                kh.sodienthoai = dienthoai;
                //kh.ngaysinh = DateTime.Parse(ngaysinh);
                data.KHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();
                ViewBag.Thongbao = "";
                Session["KiemTraDK"] = "true";
            }
            return PartialView();
        }

        //Chức năng đăng nhập của khách hàng 
        [HttpGet]
        public ActionResult DangNhap()
        {
            ViewBag.LoiDanhNhap = "";
            ViewBag.Thongbao = "";
            return PartialView();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {

            var tendn = collection["username"];
            var matkhau = collection["password"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải Nhập Tài khoản";
                return null;
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
                return null;
            }
            else
            {
                // Gán giá trị cho đối tượng được tạo mới (ad)
                KHACHHANG ad = data.KHACHHANGs.SingleOrDefault(n => n.taikhoankh == tendn && n.matkhau == matkhau);
                if (ad != null)
                {
                    // ViewBag.Thongbao = " Chúc mừng đăng nhập thành công";
                    Session["TaiKhoanKH"] = ad.tenkhachhang;
                    Session["KhachHangDangNhap"] = ad;
                    Session["avata"] = ad.anhdaidien;
                    Session["MaKH"] = ad.makh;
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng"; // Cho nhập lại một lần nữa bởi bì lần 1 k load
                    return PartialView();
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            //ViewBag.Thongbao = ""; .............
            return PartialView();
        }

        public ActionResult DangXuat()
        {
            Session["TaiKhoanKH"] = "";
            Session["avata"] = "";
            Session["KhachHangDangNhap"] = "";
            Session["count"] = "0";
            Session["MaKH"] = "";
            Session["email"] = "";
            return RedirectToAction("Index", "TrangChu");
        }
        //tai khoan khach hang
        public ActionResult EditInfor(int id)
        {
            KHACHHANG find = data.KHACHHANGs.FirstOrDefault(m => m.makh == id);
            if (find == null)
                return HttpNotFound();

            return View(find);
        }
        [HttpPost]
        public ActionResult EditInfor(int id, FormCollection collection)
        {
            //id = Convert.ToInt32(Session["MaKH"]);
            var th = data.KHACHHANGs.First(m => m.makh == id);
            var tenkhachhang = collection["tenkhachhang"];
            var sodienthoai = collection["sodienthoai"];
            var email = collection["email"];
            var diachi = collection["diachi"];
            var ngaysinh = Convert.ToDateTime(collection["ngaysinh"]);
            var anhdaidien = collection["anhdaidien"];

            th.makh = id;
            if (string.IsNullOrEmpty(tenkhachhang))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                th.tenkhachhang = tenkhachhang.ToString();
                Session["TaiKhoanKH"] = th.tenkhachhang;
                th.sodienthoai = sodienthoai.ToString();
                th.email = email.ToString();
                th.diachi = diachi.ToString();
                th.ngaysinh = ngaysinh;
                th.anhdaidien = anhdaidien;


                UpdateModel(th);
                data.SubmitChanges();
                return RedirectToAction("Index", "TrangChu");
            }
            return this.EditInfor(id);
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/AnhKhachHang/" + file.FileName));

            return file.FileName;
        }

        //đổi mật khẩu - hàm get
        public ActionResult ChangePass(int id)
        {
            KHACHHANG find = data.KHACHHANGs.FirstOrDefault(m => m.makh == id);
            if (find == null)
                return HttpNotFound();

            return View(find);
        }
        //đổi mật khẩu - hàm post
        [HttpPost]
        public ActionResult ChangePass(int id, FormCollection collection)
        {
            if (System.Web.HttpContext.Current.Session["TaiKhoanKH"].Equals(""))
            {
                System.Web.HttpContext.Current.Response.Redirect("~/TrangChu/Index");
            }
            var th = data.KHACHHANGs.First(m => m.makh == id);
            var tenkhachhang = collection["tenkhachhang"];
            var matkhauCu = collection["passCu"];
            var matkhauMoi = collection["passMoi"];
            if (matkhauCu == th.matkhau)
            {
                th.matkhau = matkhauMoi;
                UpdateModel(th);
                data.SubmitChanges();
                return RedirectToAction("Index", "TrangChu");
            }
            else
            {
                Session["ThongBao"] = "Mật khẩu cũ không chính xác!!!";

            }
            th.makh = id;

            return this.ChangePass(id);
        }

        //action send email
        public ActionResult SendEmail(string email, FormCollection collection)
        {

            var email1 = email;
            Random random = new Random();
            string maXT = "";
            for (int i = 1; i <= 1; i++)
            {
                //sử dụng random.Next(b) để hiển thị các số ngẫu nhiên giới hạn là b

                maXT = (random.Next(999999 - (100000 - 1)) + 100000).ToString();
                Session["XacThuc"] = maXT;
            }
            try
            {
                var senderemail = new MailAddress("01642027120q@gmail.com", "SHOP MIAAA");
                var receiveremail = new MailAddress(email1, "Reciver");


                var sub = "Mã Xác Nhận Quên Mật Khẩu";

                var body = "Chào bạn " + email1;
                body += "\nBạn đã yêu cầu gửi mã OTP để lấy lại mật khẩu?";
                body += "\nĐây là mã xác nhận của bạn!!!!";
                body += "\nMã xác nhận của bạn: " + maXT;

                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(senderemail.Address, "AnhQuan23092001")
                };
                using (var mess = new MailMessage(senderemail, receiveremail)
                {
                    Subject = sub,
                    Body = body
                })
                {
                    smtp.Send(mess);
                }


            }
            catch (Exception)
            {
                ViewBag.Error = "Some Error";
            }

            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        //hàm quên mật khẩu - otp gửi qua email
        public ActionResult PassEmail(FormCollection collection)
        {
            var maOTP = collection["maOTP"];
            var email = collection["email"];
            var taikhoan = collection["taikhoan"];

QLCuaHangVali/Views/NguoiDung/ChangePass.cshtml
@model QLCuaHangVali.Models.KHACHHANG
@{
    ViewBag.Title = "ChangePass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">Thông Tin Tài Khoản</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.makh)

        @using (Html.BeginForm("ChangePass", "NguoiDung", FormMethod.Post))
        {
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Tên khách hàng</label>
                <div class="col-md-3">
                    @Html.DisplayFor(model => model.tenkhachhang)
                    @Html.ValidationMessageFor(model => model.tenkhachhang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Tên tài khoản</label>
                <div class="col-md-3">

                    @Html.DisplayFor(model => model.taikhoankh)
                    @Html.ValidationMessageFor(model => model.taikhoankh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Mật Khẩu Cũ</label>
                <div class="col-md-3">
                    <input type="password" name="passCu" />
                    @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Mật Khẩu Mới</label>
                <div class="col-md-3">
                    <input type="password" name="passMoi" />
                    @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    <label class="col-md-5" style="text-align: right"></label>
                    <div class="col-md-3" style="color: red">

                        @Session["ThongBao"]
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6" style="text-align: right">
                    <input type="submit" value="Cập nhật" class="btn btn-success" />
                </div>
            </div>
        }

    </div>

}

QLCuaHangVali/Views/NguoiDung/DangKy.cshtml
@model IEnumerable<QLCuaHangVali.Models.KHACHHANG>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body modal-body-sub_agile">
                <div class="main-mailposi">
                    <span class="fa fa-envelope-o" aria-hidden="true"></span>
                </div>
                <div class="modal_body_left modal_body_left1">
                    <h3 class="agileinfo_sign">Đăng Ký</h3>
                    <p>
                        Hãy tham gia đồng hành cùng của hàng Vali! Hãy thiết lập Tài khoản của bạn.
                    </p>
                    <form action="#" method="post">
                        @using (Html.BeginForm("DangKy", "NguoiDung", FormMethod.Post))
                        {
                            <div class="styled-input agile-styled-input-top">
                                <div class="styled-input">
                                    <input type="text" placeholder="Họ và tên" name="name" required="">
                                </div>
                                <input type="text" placeholder="Tên tài khoản" name="username" required="">
                            </div>
                            <div class="styled-input">
                                <input type="email" placeholder="E-mail" name="Email" required="">
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Password" name="password" id="password1" required="">
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Nhập lại mật khẩu" name="ConfirmPassword" id="password2" required="">
                            </div>
                            <div class="styled-input agile-styled-input-top">
                                <input type="tel" placeholder="VD: (+84) 976-666-666" id="sodienthoai" name="sodienthoai" required=""
                                       pattern="0[3,5,7,8,9]{1}[0-9]{2}[0-9]{3}[0-9]{3}">
                            </div>

                            <input class="DangKyTK" type="submit" value="Đăng ký">
                        }
                    </form>
                    <p>
                        <input type="checkbox" />
                        <a href="#">Bằng cách nhấp vào đăng ký, tôi đồng ý với các điều khoản của bạn</a>
                    </p>
                </div>
            </div>
        </div>
        <!-- //Modal content-->
    </div>
</div>

QLCuaHangVali/Views/NguoiDung/DangNhap.cshtml
@model IEnumerable<QLCuaHangVali.Models.KHACHHANG>
 
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            Modal content
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close btn_close_login" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body modal-body-sub_agile">
                    <div class="main-mailposi">
                        <span class="fa fa-envelope-o" aria-hidden="true"></span>
                    </div>
                    <div class="modal_body_left modal_body_left1">

                        <h3 class="agileinfo_sign">Đăng Nhập </h3>
                        <p>
                            Đăng nhập ngay bây giờ, Hãy bắt đầu Mua sắm Vali của bạn. Không có tài khoản?
                            <a href="#" data-toggle="modal" data-target="#myModal2">
                                Đăng ký ngay
                            </a>
                        </p>
                       
                        <form action="" method="post">
                            @using (Html.BeginForm("Index", "TrangChu", FormMethod.Post))
                            {
                                <div class="styled-input agile-styled-input-top">
                                    <input type="text" placeholder="Nhập tài khoản" name="username" required="">
                                </div>
                                <p class="check_login2">@ViewData["Loi1"]</p>
                                <div class="styled-input">
                                    <input type="password" placeholder="Mật khẩu" name="password" required="">
                                </div>
                                <a href="@Url.Action("PassEmail", "NguoiDung" )" style="color: red">
                                    Quên mật khẩu?
                                </a>
                                <a href="@Url.Action("XacThuc", "NguoiDung" )" style="color: red">
                                    Xác thực tài khoản?
                                </a>
                                <h4 class="check_login1" style="color: red; font-size: 16px; text-align: center;">@ViewBag.Thongbao</h4>
                                <p class="check_login3">@ViewData["Loi2"]</p>
                                <input type="submit" value="Đăng Nhập" class="dangnhap">
                            }
                        </form>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
  </div>

QLCuaHangVali/Views/NguoiDung/EditInfor.cshtml
@model QLCuaHangVali.Models.KHACHHANG

@{
    ViewBag.Title = "EditInfor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">Chỉnh Sửa Thông Tin</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.makh)
        <div class="form-group">
            <label class="col-md-5" style="text-align: right">
                <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                       style="display:none;" />
                <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            </label>
            <div class="col-md-3" style="text-align: center">
                @Html.EditorFor(model => model.anhdaidien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.anhdaidien, "", new { @class = "text-danger" })

                <img src="~/Content/AnhKhachHang/@Model.anhdaidien" style="border-radius: 50%; height: 120px; width: 120px;" id="pictureUpload" />
            </div>
        </div>
        <!--  Lam nut chon anh  -->
        @section upload
{
            <script>
            $(function () {
                $('#btnUpload').click(function () {
                    $('#fileUpload').trigger('click');
                });
            });
            $('#fileUpload').change(function () {
                if (window.FormData !== undefined) {
                    var fileUpload = $('#fileUpload').get(0);
                    var files = fileUpload.files;
                    var formData = new FormData();
                    formData.append('file', files[0]);

                    $.ajax(
                        {
                            type: 'POST',
                            url: '/NguoiDung/ProcessUpload',
                            contentType: false,
                            processData: false,
                            data: formData,
                            success: function (urlImage) {

                                $('#pictureUpload').attr('src', "/Content/AnhKhachHang/" +  urlImage);
                                $('#anhdaidien').val(urlImage);
                            },
                            error: function (err) {
                                alert('Error ', err.statusText);
                            }
                        });
                }
            });
            </script>
        }
        <!--  End- Lam nut chon anh  -->
        <div class="form-group">
            <label class="col-md-5" style="text-align: right">Tên khách hàng</label>
            <div class="col-md-3">
                @Html.EditorFor(model => model.tenkhachhang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenkhachhang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-5" style="text-align: right">Số điện thoại</label>
            <div class="col-md-3">
                @Html.EditorFor(model => model.sodienthoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sodienthoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-5" style="text-align: right">Email</label>
            <div class="col-md-3">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-5" style="text-align: right">Địa chỉ</label>
            <div class="col-md-3">
                @Html.EditorFor(model => model.diachi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.diachi, "", new { @class = "text-danger" })
            </div>
        </div>



        @*<div class="form-group">
              <label class="col-md-5" style="text-align: right">Tên khách hàng</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.matkhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <label class="col-md-5" style="text-align: right">Ngày sinh</label>
            <div class="col-md-3">
                @Html.EditorFor(model => model.ngaysinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaysinh, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-6" style="text-align: right">
                <input type="submit" value="Cập nhật" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

QLCuaHangVali/Views/NguoiDung/PassEmail.cshtml
@model QLCuaHangVali.Models.KHACHHANG
@{
    ViewBag.Title = "PassEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">Quên Mật Khẩu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        @using (Html.BeginForm("PassEmail", "NguoiDung", FormMethod.Post))
        {
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Tài khoản </label>
                <div class="col-md-3">
                    <input type="text" name="taikhoan" required />
                    @Html.ValidationMessageFor(model => model.taikhoankh, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Vui lòng nhập email </label>
                <div class="col-md-3">
                    <input type="text" name="email" value="" id="emailUser" required /> <input type="button" name="name" value="Gửi mã" class="addtocart" />

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Nhập mã OTP </label>
                <div class="col-md-3">
                    <input type="text" name="maOTP" required />

                </div>
            </div>



            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Mật Khẩu Mới</label>
                <div class="col-md-3">
                    <input type="password" name="matKhauMoi" required />
                    @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Nhập lại mật khẩu</label>
                <div class="col-md-3">
                    <input type="password" name="repass" required />
                    @Html.ValidationMessageFor(model => model.matkhau, "", new { @class = "text-danger" })
                </div>
            </div>
            @Session["ThongBao"]
            <div class="form-group">
                <div class="col-md-offset-2 col-md-6" style="text-align: right">
                    <input type="submit" value="Xác nhận" class="btn btn-success" />

                </div>
            </div>

        }

    </div>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @section sendEmail {
        <script type="text/javascript">
    $(function () {
        $(".addtocart").click(function () {
            var model = {};

            model.email = $("#emailUser").val();

            debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Action("SendEmail", "NguoiDung")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Vui lòng kiểm tra email',
                        showConfirmButton: false,
                        timer: 2000
                    });
                },
                error: function () {
                    Swal.fire({
                        icon: 'error',
                        title: 'Thêm giỏ hàng thất bại \n Bạn cần đăng nhập',
                        text: 'Vui lòng thử lại!',
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            });
            return false;
        });
    });
        </script>
    }
}

QLCuaHangVali/Views/NguoiDung/XacThuc.cshtml
@model QLCuaHangVali.Models.KHACHHANG
@{
    ViewBag.Title = "XacThuc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">Xác Thực Tài Khoản</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        @using (Html.BeginForm("PassEmail", "NguoiDung", FormMethod.Post))
        {
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Tài khoản </label>
                <div class="col-md-3">
                    <input type="text" name="taikhoan" required />
                    @Html.ValidationMessageFor(model => model.taikhoankh, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Vui lòng nhập email </label>
                <div class="col-md-3">
                    <input type="text" name="email" value="" id="emailUser" required /> <input type="button" name="name" value="Gửi mã" class="addtocart" />

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-5" style="text-align: right">Nhập mã OTP </label>
                <div class="col-md-3">
                    <input type="text" name="maOTP" required />

                </div>
            </div>






            <div class="form-group">
                <div class="col-md-offset-2 col-md-6" style="text-align: right">
                    <input type="submit" value="Xác nhận" class="btn btn-success" />
                </div>
            </div>
        }

    </div>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @section sendEmail {
        <script type="text/javascript">
    $(function () {
        $(".addtocart").click(function () {
            var model = {};

            model.email = $("#emailUser").val();

            debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Action("SendEmail", "NguoiDung")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    Swal.fire({
                        position: 'center',
                        icon: 'success',
                        title: 'Vui lòng kiểm tra email',
                        showConfirmButton: false,
                        timer: 2000
                    });
                },
                error: function () {
                    Swal.fire({
                        icon: 'error',
                        title: 'Thêm giỏ hàng thất bại \n Bạn cần đăng nhập',
                        text: 'Vui lòng thử lại!',
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            });
            return false;
        });
    });
        </script>
    }
}